<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-08-30T04:32:15 IST" name="Default suite" finished-at="2025-08-30T04:32:16 IST" duration-ms="206">
    <groups>
    </groups>
    <test started-at="2025-08-30T04:32:15 IST" name="Default test" finished-at="2025-08-30T04:32:16 IST" duration-ms="206">
      <class name="day15.DependencyMethods">
        <test-method signature="openApp()[pri:1, instance:day15.DependencyMethods@367ffa75]" started-at="2025-08-30T04:32:15 IST" name="openApp" finished-at="2025-08-30T04:32:15 IST" duration-ms="29" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="login()[pri:2, instance:day15.DependencyMethods@367ffa75]" started-at="2025-08-30T04:32:15 IST" name="login" finished-at="2025-08-30T04:32:15 IST" depends-on-methods="day15.DependencyMethods.openApp" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="search()[pri:3, instance:day15.DependencyMethods@367ffa75]" started-at="2025-08-30T04:32:15 IST" name="search" finished-at="2025-08-30T04:32:15 IST" depends-on-methods="day15.DependencyMethods.login" duration-ms="14" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at day15.DependencyMethods.search(DependencyMethods.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- search -->
        <test-method signature="advsearch()[pri:4, instance:day15.DependencyMethods@367ffa75]" started-at="2025-08-30T04:32:15 IST" name="advsearch" finished-at="2025-08-30T04:32:15 IST" depends-on-methods="day15.DependencyMethods.search, day15.DependencyMethods.login" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method day15.DependencyMethods.advsearch() on instance day15.DependencyMethods@367ffa75 depends on not successfully finished methods 
[day15.DependencyMethods.search() on instance day15.DependencyMethods@367ffa75
day15.DependencyMethods.login() on instance day15.DependencyMethods@367ffa75]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method day15.DependencyMethods.advsearch() on instance day15.DependencyMethods@367ffa75 depends on not successfully finished methods 
[day15.DependencyMethods.search() on instance day15.DependencyMethods@367ffa75
day15.DependencyMethods.login() on instance day15.DependencyMethods@367ffa75]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- advsearch -->
        <test-method signature="logout()[pri:5, instance:day15.DependencyMethods@367ffa75]" started-at="2025-08-30T04:32:16 IST" name="logout" finished-at="2025-08-30T04:32:16 IST" depends-on-methods="day15.DependencyMethods.login" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- day15.DependencyMethods -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
